string= 'Hello World'

print(string.upper())
print(string.lower())
print(string.count('l'))
print(string.find('l'))
print(string.replace('l','z'))
print(string.islower())
print(string.isupper())
print(string.upper())
print(string.isalnum())
print(string.isalpha())
print(string.isdigit())
print(string.index('H'))
print(string.strip('d'))
